App_Blog/urls.py
from django.urls import path
from App_Blog import views


app_name = 'App_Blog'
urlpatterns = [
    path('', views.blog_list, name='blog_list')
]

App_Login/urls.py
from django.urls import path
from App_Login import views


app_name = 'App_Login'


urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile', views.user_info_update, name='update_profile'),
    path('password/', views.pass_change, name='pass_change'),
    path('add-profile-pic/', views.add_profile_pic, name='add_profile_pic'),
    path('update-profile-pic/', views.update_profile_pic, name='update_profile_pic')
]

buniadi/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name='Put a Title')
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name='What is your mind?')
    blog_image = models.ImageField(upload_to='blog_image', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment


class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


class userProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import userProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

class profilePic(forms.ModelForm):
    class Meta:
        model = userProfile
        fields = ('profile_pic',)

App_Blog/views.py
from django.shortcuts import render

# Create your views here.


def blog_list(request):
    return render(request, "App_Blog/blog_list.html", context={})

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, profilePic

# Create your views here.


def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered}
    return render(request, 'App_Login/signup.html', context=dict)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

    return render(request, 'App_Login/login.html', context={'form':form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})

@login_required
def user_info_update(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form':form})


@login_required
def pass_change(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data = request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'App_Login/change_pass.html', context={'form':form})

@login_required
def add_profile_pic(request):
    form = profilePic()
    if request.method == 'POST':
        form = profilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile_pic.html', context={'form':form})


@login_required
def update_profile_pic(request):
    form = profilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = profilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile_pic.html', context={'form':form})

buniadi/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


def index(request):
    return HttpResponseRedirect(reverse('App_Blog:blog_list'))

templates/App_Blog/blog_details.html
{% extends 'base.html'%}
{% block title_block%}Home{% endblock %}
{% block body_block %}
Blog details
{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html'%}
{% block title_block%}Home{% endblock %}
{% block body_block %}
I am a home page
{% endblock %}

templates/App_Blog/ceate_blog.html
{% extends 'base.html'%}
{% block title_block%}Home{% endblock %}
{% block body_block %}
I am a home page
{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html'%}
{% block title_block%}Home{% endblock %}
{% block body_block %}
I am a home page
{% endblock %}

templates/App_Blog/my_blog.html
{% extends 'base.html'%}
{% block title_block%}Home{% endblock %}
{% block body_block %}
I am a home page
{% endblock %}

templates/App_Login/change_pass.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %} Edit Account {% endblock %}
{% block body_block%}
<div class="card">
    <div class="card-header">
        Password Update
    </div>
    <div class="card-body">
        <form class="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Change Password</button>
        </form>
    </div>
</div>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %} Edit Account {% endblock %}
{% block body_block%}
<div class="card">
    <div class="card-header">
        Edit Account
    </div>
    <div class="card-body">
        <form class="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Edit Account</button>
        </form>
    </div>
</div>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Login{% endblock %}
{% block body_block %}
<div class="card">
    <div class="card-header">
        Login Here
    </div>
    <div class="card-body">
        <form class="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Loin</button>
        </form>
        <br />
        <p>Already have an account? <a href="">Login Here</a></p>
    </div>
</div>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title_block %}Profile{% endblock %}
{% block body_block %}
<h2>Your Profile</h2>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px">
<br>
<br>
<a href="{% url 'App_Login:update_profile_pic' %}" class="btn btn-info btn-sm">Update Image</a>
{% else %}
<img src="/media/profile_pics/avatar.png">
<br>
<br>
<a href="{% url 'App_Login:add_profile_pic' %}" class="btn btn-info btn-sm">Add Image</a>
{% endif %}
<br>
<br>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Full name: {{ user.first_name }}{{ user.last_name }}</p>
<br />
<a href="{% url 'App_Login:update_profile' %}">Change Profile Info</a>
{% endblock %}

templates/App_Login/profile_pic.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %} Edit Account {% endblock %}
{% block body_block%}
<div class="card">
    <div class="card-header">
        Edit Account
    </div>
    <div class="card-body">
        <form class="" method="POST" enctype="multipart/form-data">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Image</button>
        </form>
    </div>
</div>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}Create New Account {% endblock %}
{% block body_block%}
{% if registered %}
<div class="alert alert-success">
    Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}
<div class="card">
    <div class="card-header">
        Create New Account
    </div>
    <div class="card-body">
        <form class="" method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-success btn-sm">Create Account</button>
        </form>
        <br />
        <p>Already have an account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
    </div>
</div>
{% endif %}
{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{%block title_block%}Blogs{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
       <li class="nav-item dropdown pul-right">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>{{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}"><i class="fa fa-users" aria-hidden="true"></i></i>Profile</a>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}"><i class="fa fa-sign-in" aria-hidden="true"></i>Logout</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:signup' %}">Register</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
      </li>
      {% endif %}
  </ul>
</nav>
</div>
<div class="container" style="padding-top:20px">
{% block body_block %}

{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>